openapi: 3.0.0

info:
  title: "RP Flask REST API"
  description: "An API example"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas: !include include.d/customerData.yaml

paths:
  /customers:
    get:
      operationId: "customers.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read customer list"
    post:
      operationId: "customers.create"
      tags:
        - People
      summary: "Create a customer"
      requestBody:
        x-body-name: "customer"
        description: "Customer to create"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerData"
      responses:
        "201":
          description: "Successfully created customer"
